### ISSUE TITLE
Disable title and legend

### ISSUE THREAD

**Issue by linusnorton** [extenda/structurizr-to-png#10]
Is it possible to add a cli argument to remove the title and legend?

**Comment by sasjo** [comment]
With the recent upgrade of the Structurizr dependency, this is now possible to control in the view definition. It's unfortunately renderer specific, but this is the out-of-the-box support at least.

```
  views {
    systemContext system {
      include *
    }

    container system {
      include *
      properties {
        plantuml.title false
        c4plantuml.legend false
      }
    }
  }
```

I'll open up a PR to include this information in the README.
