### ISSUE TITLE
is there an option to run the docker container with a debug log level?

### ISSUE THREAD

**Issue by platzhersh** [extenda/structurizr-to-png#48]
We are currently using the container to generate c4 model pngs in our project. 
When I run it locally it takes extremely long - mainly because I am using an M1 macbook (linux/arm64/v8).

Sometimes it takes so long that I am wondering whats actually happening in the container. Therefor it would be cool to have a param or env setting to run the container with a more verbose log level

**Comment by sasjo** [comment]
The support will be added through the `log-level` argument. Valid vales are the Logback levels (ERROR, WARN, INFO, DEBUG, TRACE).

```
./dsl2.png --log-level=TRACE
```
