### ISSUE TITLE
Does not seem to apply any styles

### ISSUE THREAD

**Issue by platzhersh** [extenda/structurizr-to-png#76]
We are using quite some `styles` to make our c4model more easy to read. i.e.

```
    styles {
            element "web" {
                shape "WebBrowser"
            }
    }
```

When I use `extenda/structurizr-to-png` docker image to generate pngs, these styles do not end up being applied for the generated png images.

Am I missing a parameter / config? Or is this not implemented?

**Comment by platzhersh** [comment]
I just played around, and when using `--render-with structurizr` they seem to be applied, although not exactly correct.

Should I move my styles into a theme?

**Comment by platzhersh** [comment]
i.e. the following shapes seem to be not supported (with structurizr): `WebBrowser`, `Circle`,

**Comment by sasjo** [comment]
Hi, the shape support depends on the renderer as you've discovered. The structurizr renderer is probably the most up-to-date nowadays feature-wise. We're lagging behind a bit on the structurizr dependencies and I'll see if we can get the bumped dependencies merged.
