### ISSUE TITLE
Custom Theme

### ISSUE THREAD

**Issue by NicoFischer** [extenda/structurizr-to-png#9]
Hi,

is there a way to use a custom theme with this?

The structurizr theme like used in the structurizr lite would be my goal.

Or are there limitations with the cli?

Best Regards,

Nico

**Comment by sasjo** [comment]
I believe custom themes should work as long as they are served from a reachable http(s) URL. Structurizr doesn't seem to support local theme files. The default theme is always added/appended by structurizr-to-png and if this interferes with your custom theme we could support disabling the default theme with a cli flag.

**Comment by revjtanton** [comment]
tried with this: `theme https://static.structurizr.com/themes/amazon-web-services-2022.04.30/theme.json`
and this: `themes https://static.structurizr.com/themes/amazon-web-services-2022.04.30/theme.json https://static.structurizr.com/themes/amazon-web-services-2020.04.30/theme.json`

Neither keep the formatting. Am I missing something?
